### PR TITLE
add new m1.medium instance type

### PR DESCRIPTION
**Pull request by jtriley**

### CODE REVIEW

**Comment by jtriley** [comment]
@garnaat beat me to it :P

**Comment by garnaat** [comment]
lol.  I haven't actually fired up an m1.medium yet so I'm not totally sure if that is the correct disk config.  I'll try one out sometime today just to validate.

**Comment by jtriley** [comment]
Yea I was just guessing as well. I just fired up an instance of m1.medium a few minutes ago to test whether it can handle S3-backed AMIs (wasn't sure if this was another micro instance that can only use EBS). Here's the fdisk output:

```
root@master:~# fdisk -l

Disk /dev/sda1: 10.7 GB, 10737418240 bytes
255 heads, 63 sectors/track, 1305 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000

Disk /dev/sda1 doesn't contain a valid partition table

Disk /dev/sda2: 429.5 GB, 429461078016 bytes
255 heads, 63 sectors/track, 52212 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000
```

Anything else you'd like to know before I shut this thing down? Got about an hour left ;)

**Comment by garnaat** [comment]
No, that should do it.  Thanks!

Btw, are you at pycon this year?

**Pull request closed without merging**
